# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Azure Resource Manager (ARM) Template Deployment
      uses: whiteducksoftware/azure-arm-action@v2.2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Provide the name of a resource group.
        resourceGroupName: 'armgh-rg'
        # Specify the path to the Azure Resource Manager template.
        templateLocation: './template.json'
        # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group).
        #deploymentMode: Incremental
        # Supply deployment parameter values.
        parameters: './parameters.json'
